# Generated by Django 4.1 on 2022-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hobby',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.hobby'),
        ),
    ]
