# Generated by Django 4.1 on 2022-08-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hobby',
            field=models.ManyToManyField(to='myapp.hobby'),
        ),
    ]
